version: "3"
services:
  postgres:
    image: "postgres:15-alpine"
    container_name: blog-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DATABASE:?}
      - PGDATA=${PGDATA:?}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: "redis:latest"
    restart: unless-stopped
    container_name: blog-redis
    ports:
      - "6379:6379"
    networks:
      - network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: blog
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    networks:
      - network

networks:
  network:
    driver: bridge
